option(${PROJECT_NAME}_ENABLE_OMP "Enable OpenMP in examples." OFF)
option(${PROJECT_NAME}_BUILD_TEST "Build tests." OFF)
option(${PROJECT_NAME}_BUILD_EXAMPLES "Build examples." OFF)
option(${PROJECT_NAME}_TEST_COVERAGE "Test code coverage (using gcov, needs compilation with gcc)." OFF)
option(${PROJECT_NAME}_ENABLE_CLANG_TIDY "Enable static analysis with clang-tidy." OFF)

message("========================================")
message("= Configuring torrepp:                 =")
message(" * Build type:       ${CMAKE_BUILD_TYPE}")
message(" * Build test:       ${${PROJECT_NAME}_BUILD_TEST}")
message(" * Build benchmark:  ${${PROJECT_NAME}_BUILD_BENCHMARK}")
message(" * Build examples:   ${${PROJECT_NAME}_BUILD_EXAMPLES}")
message(" * \t|> with OpenMP:  ${${PROJECT_NAME}_ENABLE_OMP}")
message(" * Test coverage:    ${${PROJECT_NAME}_TEST_COVERAGE}")
message(" * Clang-tidy:       ${${PROJECT_NAME}_ENABLE_CLANG_TIDY}")
message("========================================")
